### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by dtrunk90** [dtrunk90/spring-boot-thymeleaf3#1]
Discussion based on https://github.com/mxab/thymeleaf-extras-data-attribute/pull/7#issuecomment-221113888

**Comment by robvanderboom** [comment]
Hi, 

aa yes the message source also tries to 'translate', you mean that first thyme leaf translate the variable "${article.title}" and them the result of this is translated by message source and therefore fails ?
Within my project it makes no difference if i yes or no set the message source on the templateEngine..

**Comment by dtrunk90** [comment]
These were just some tests. Thymeleaf cannot resolve the message and therefore it tries to parse its result (`??hello_en_US??`) as an expression.

It must be a misconfiguration of either Thymeleaf or Spring.

**Comment by robvanderboom** [comment]
aaah ok thanks a lot, i thought it depended on setting the message source if ir worked ;-)

thanks so far, i will also debug and try to find more details about this issue

**Comment by dtrunk90** [comment]
Got it! You need to add `@Bean` to the configuration method which returns the TemplateEngine and make it public instead of private. See: https://gist.github.com/seanhinkley/6eab2130ceea857c160b#file-thymeleafconfig-java-L45

**Comment by dtrunk90** [comment]
I've created an issue to update the migration guide: https://github.com/thymeleaf/thymeleaf/issues/504
